/** Shared page metadata, so every route emits a complete Open Graph card. */

import type { Metadata } from 'next';
import siteConfig from '@/lib/site-config';

/**
 * The social card image, shared by the root layout and every page.
 *
 * Generated by the route handler at app/opengraph-image.png/route.tsx. The
 * route segment is literally named `opengraph-image.png`, so the static export
 * writes a real .png file and GitHub Pages serves it as image/png (an
 * extensionless file would be octet-stream, which some scrapers reject).
 */
export const OG_IMAGE = {
  url: '/opengraph-image.png',
  width: 1200,
  height: 630,
  alt: 'Valentine Mohaugen, Ph.D. Student in Quantum Machine Learning, Cybersecurity, and Cyber-Physical Systems at Clemson University',
} as const;

interface PageMetadataOptions {
  /** Page title, without the site-name suffix. */
  title: string;
  description: string;
  /** Route path with a trailing slash, e.g. "/cv/". */
  path: string;
  /** Longer description for social cards, when it differs from `description`. */
  ogDescription?: string;
}

/**
 * Build a page's metadata with a complete `openGraph` block.
 *
 * Next merges `metadata` only one level deep, so a page that declares its own
 * `openGraph` object REPLACES the root one rather than extending it. Writing
 * these blocks by hand silently dropped og:image, og:type, og:site_name and
 * og:locale from every subpage, leaving them with no social preview image.
 * Routing them through this helper is what keeps that from happening again.
 *
 * @param options - Title, description, route path, and optional social copy.
 * @returns Metadata with title, description, and a full openGraph block.
 */
export function pageMetadata({
  title,
  description,
  path,
  ogDescription,
}: PageMetadataOptions): Metadata {
  return {
    title,
    description,
    openGraph: {
      title: `${title} · ${siteConfig.name}`,
      description: ogDescription ?? description,
      url: path,
      siteName: siteConfig.name,
      locale: 'en_US',
      type: 'website',
      images: [OG_IMAGE],
    },
  };
}
